updated github action to deploy to server

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,3 +34,27 @@ jobs:
           file: ./Dockerfile
           push: true
           tags: ghcr.io/${{ github.repository }}/hms_frontend:latest
+
+      - name: Deploy to server
+        env:
+          PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
+          HOSTNAME: ${{ secrets.SERVER_HOST }}
+          USER_NAME: ${{ secrets.SERVER_USER }}
+        run: |
+          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
+          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
+            # Login to GitHub Container Registry
+            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+            
+            # Pull the latest image
+            docker pull ghcr.io/${{ github.repository_owner }}/channel-clinic/hms_frontend:latest
+            
+            # Stop the existing container (if it exists)
+            docker stop hms_frontend || true
+            docker rm hms_frontend || true
+            
+            # Run the new container
+            docker run -d --name hms_frontend -p 80:80 ghcr.io/${{ github.repository_owner }}/channel-clinic/hms_frontend:latest
+            
+            # Cleanup
+            docker system prune -f
